export const HYPNOSIS_LINKS = {
  preDrinkHypnosis: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/pre-drinking-session.mp3',
  hypnosisForAdventure: {
    day1: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-01.mp3',
    day2: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-02.mp3',
    day3: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-03.mp3',
    day4: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-04.mp3',
    day5: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-05.mp3',
    day6: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-06.mp3',
    day7: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-07.mp3',
    day8: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-08.mp3',
    day9: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-09.mp3',
    day10: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-10.mp3',
    day11: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-11.mp3',
    day12: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-12.mp3',
    day13: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-13.mp3',
    day14: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-14.mp3',
    day15: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-15.mp3',
    day16: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-16.mp3',
    day17: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-17.mp3',
    day18: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-18.mp3',
    day19: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-19.mp3',
    day20: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-20.mp3',
    day21: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-21.mp3',
    day22: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-22.mp3',
    day23: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-23.mp3',
    day24: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-24.mp3',
    day25: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-25.mp3',
    day26: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-26.mp3',
    day27: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-27.mp3',
    day28: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-28.mp3',
    day29: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-29.mp3',
    day30: 'https://unconscious-moderation.s3.us-east-1.amazonaws.com/hypnosis/hypnosis-for-adventure/month-one/day-30.mp3',
  },
} as const
