const MASTER_CLASS = {
  'day-1': {
    title: 'Navigating Change',
    author: 'Jay Shetty',
    trailer: 'https://www.youtube.com/watch?v=A4LbNiKX1Dk',
    link: 'https://www.masterclass.com/classes/navigating-change',
  },
  'day-2': {
    title: 'Teaches Mindfulness and meditation',
    author: 'Jon Kabat Zinn',
    trailer: 'https://www.youtube.com/watch?v=u7FrtC51Xwo',
    link: 'https://www.masterclass.com/classes/jon-kabat-zinn-teaches-mindfulness-and-meditation',
  },
  'day-3': {
    title: 'Small habits that make a big impact on you life',
    author: 'James Clear',
    trailer: 'https://www.youtube.com/watch?v=Esw4p0C5u-g',
    link: 'https://www.masterclass.com/classes/small-habits-that-make-a-big-impact-on-your-life',
  },
  'day-4': {
    title: 'Teaches a winning mindset',
    author: 'Lewis Hamilton',
    trailer: 'https://www.youtube.com/watch?v=Vka_H7YiTGI',
    link: 'https://www.masterclass.com/classes/lewis-hamilton-teaches-a-winning-mindset',
  },
  'day-5': {
    title: 'The Science of Sleep',
    author: 'Matthew Walker',
    trailer: 'https://www.youtube.com/watch?v=106zCmbMKYY',
    link: 'https://www.masterclass.com/classes/matthew-walker-teaches-the-science-of-better-sleep',
  },
  'day-6': {
    title: 'Effective and Authentic Communication',
    author: 'Robin Roberts',
    trailer: 'https://www.youtube.com/watch?v=ZQuSpFaQFgM',
    link: 'https://www.masterclass.com/classes/robin-roberts-teaches-effective-and-authentic-communication',
  },
  'day-7': {
    title: 'The Art of Negotiation',
    author: 'Chris Voss',
    trailer: 'https://www.youtube.com/watch?v=q8rX4GUZSsU',
    link: 'https://www.masterclass.com/classes/chris-voss-teaches-the-art-of-negotiation',
  },
  'day-8': {
    title: 'The Power of Resilience',
    author: 'Hillary Rodham Clinton',
    trailer: 'https://www.youtube.com/watch?v=mcPsVWwBCuo',
    link: 'https://www.masterclass.com/classes/hillary-rodham-clinton-teaches-the-power-of-resilience',
  },
  'day-9': {
    title: 'Intentional Eating',
    author: 'Michael Pollan',
    trailer: 'https://www.youtube.com/watch?v=yLpJ0C1Ggug',
    link: 'https://www.masterclass.com/classes/michael-pollan-teaches-intentional-eating',
  },
  'day-10': {
    title: 'The Power of Mindset',
    author: 'Carol Dweck, David Yeager, Steve Young, Jeremy Bohannon, and Lorena Tareszkiewicz Seidel',
    trailer: 'https://www.youtube.com/watch?v=iYSulLpqcyg',
    link: 'https://www.masterclass.com/classes/power-of-mindset',
  },
  'day-11': {
    title: 'In Practice: Your Anxiety Toolkit',
    author: 'Dr. Alexandra Solomon',
    trailer: 'https://www.youtube.com/watch?v=pIza9QsjUCU',
    link: 'https://www.masterclass.com/series/in-practice-series',
  },
  'day-12': {
    title: 'Mental Strength',
    author: 'Robin Arzon',
    trailer: 'https://www.youtube.com/watch?v=tJAH593Oon8',
    link: 'https://www.masterclass.com/classes/robin-arzon-teaches-mental-strength',
  },
  'day-13': {
    title: 'The Power of Empathy',
    author: 'Pharrell Williams, Robin Arzón, Roxane Gay, Walter Mosley, Robert Reffkin, Gloria Steinem, and Cornel West',
    trailer: 'https://www.youtube.com/watch?v=9pZXfaZA_CM',
    link: 'https://www.masterclass.com/classes/the-power-of-empathy-with-pharrell-williams-and-noted-co-instructors',
  },
  'day-14': {
    title: 'Using Humor to Make Your Mark',
    author: 'Kevin Hart',
    trailer: 'https://www.youtube.com/watch?v=p-43LwVmUuQ',
    link: 'https://www.masterclass.com/classes/using-humor-to-make-your-mark',
  },
  'day-15': {
    title: 'Yoga Foundations',
    author: 'Donna Farhi Teaches',
    trailer: 'https://www.youtube.com/watch?v=KuvMwGJ6t3Y',
    link: 'https://www.masterclass.com/classes/donna-farhi-teaches-yoga-foundations',
  },
  'day-16': {
    title: 'The Art of Intelligence',
    author: 'Brian Carbaugh, Dawn Meyerriecks, and Michael Morell',
    trailer: 'https://www.youtube.com/watch?v=bupn1w3PzE4',
    link: 'https://www.masterclass.com/classes/the-art-of-intelligence',
  },
  'day-17': {
    title: 'The Athlete\'s Mindset',
    author: 'Wayne Gretzky',
    trailer: 'https://www.youtube.com/watch?v=jM8dsk-zwIc',
    link: 'https://www.masterclass.com/classes/wayne-gretzky-teaches-the-athlete-s-mindset',
  },
  'day-18': {
    title: 'Purposeful Communication',
    author: 'George Stephanopoulos',
    trailer: 'https://www.youtube.com/watch?v=dwR133-jkBo',
    link: 'https://www.masterclass.com/classes/george-stephanopoulos-teaches-purposeful-communication',
  },
  'day-19': {
    title: 'Using Ancient Wisdom to Solve Modern Problems',
    author: 'Ryan Holiday',
    trailer: 'https://www.youtube.com/watch?v=1yh2Y-bIan0',
    link: 'https://www.masterclass.com/series/using-ancient-wisdom-to-solve-modern-problems',
  },
  'day-20': {
    title: 'Science and Problem-Solving',
    author: 'Bill Nye',
    trailer: 'https://www.youtube.com/watch?v=GFiQB6Lbi-U',
    link: 'https://www.masterclass.com/classes/bill-nye-teaches-science-and-problem-solving',
  },
  'day-21': {
    title: 'Self-Expression and Authenticity',
    author: 'RuPaul',
    trailer: 'https://www.youtube.com/watch?v=HzBX9wXtLxU',
    link: 'https://www.masterclass.com/classes/rupaul-teaches-self-expression-and-authenticity',
  },
  'day-22': {
    title: 'Prepare to be Unprepared',
    author: 'Amy Poehler',
    trailer: 'https://www.youtube.com/watch?v=nSFWkf9p4cQ',
    link: 'https://www.masterclass.com/classes/prepare-to-be-unprepared',
  },
  'day-23': {
    title: 'Brain Health',
    author: 'Dr. Wendy Suzuki, Dr. Lisa Feldman Barrett, Dr. Uma Naidoo, and Gregory Gourdet',
    trailer: 'https://www.youtube.com/watch?v=sQ9XhSkXfVw',
    link: 'https://www.masterclass.com/series/brain-health',
  },
  'day-24': {
    title: 'Fitness and Wellness Fundamentals',
    author: 'Joe Holder',
    trailer: 'https://www.youtube.com/watch?v=OVcNRUESqvA',
    link: 'https://www.youtube.com/watch?v=OVcNRUESqvA',
  },
  'day-25': {
    title: 'Gut Health',
    author: 'David Zilber, Dr. Emeran Mayer, and Erica Sonnenburg & Justin Sonnenburg',
    trailer: 'https://www.youtube.com/watch?v=FC1EvPAwkzk',
    link: 'https://www.masterclass.com/series/gut-health',
  },
  'day-26': {
    title: 'Relational Intelligence',
    author: 'Esther Perel',
    trailer: 'https://www.youtube.com/watch?v=WWIDZq4gCGY',
    link: 'https://www.masterclass.com/classes/esther-perel-teaches-relational-intelligence',
  },
  'day-27': {
    title: 'Tell a Great Story',
    author: 'Michael Lewis',
    trailer: 'https://www.youtube.com/watch?v=9EhRoVj0kfE',
    link: 'https://www.masterclass.com/series/tell-a-great-story',
  },
  'day-28': {
    title: 'Skin Health',
    author: 'Dr. Shereene Idriss, Dr. Michelle Henry, Ron Robinson, Dr. April Armstrong',
    trailer: 'https://www.youtube.com/watch?v=fk-VTgdPqAA',
    link: 'https://www.masterclass.com/skin-health',
  },
  'day-29': {
    title: 'Critical Leadership Training',
    author: 'Jocko Willink',
    trailer: 'https://www.youtube.com/watch?v=U_wWlm8xJL8',
    link: 'https://www.masterclass.com/classes/critical-leadership-training-with-navy-seal-officer-jocko-willink-continuous-cut',
  },
  'day-30': {
    title: 'Reframe Your Thinking',
    author: 'Ava DuVernay',
    trailer: 'https://www.youtube.com/watch?v=QPz1yXgfsSU',
    link: 'https://www.masterclass.com/classes/reframe-your-thinking',
  },
} as const

export { MASTER_CLASS }
